[2025-06-27T04:48:54.188+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T04:48:54.234+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark manual__2025-06-27T04:48:47.202496+00:00 [queued]>
[2025-06-27T04:48:54.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark manual__2025-06-27T04:48:47.202496+00:00 [queued]>
[2025-06-27T04:48:54.243+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T04:48:54.275+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Structure_Data_With_Spark> on 2025-06-27 04:48:47.202496+00:00
[2025-06-27T04:48:54.279+0000] {standard_task_runner.py:64} INFO - Started process 221 to run task
[2025-06-27T04:48:54.282+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_pipeline', 'Structure_Data_With_Spark', 'manual__2025-06-27T04:48:47.202496+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1lgedrfe']
[2025-06-27T04:48:54.283+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask Structure_Data_With_Spark
[2025-06-27T04:48:54.794+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_processing_pipeline.Structure_Data_With_Spark manual__2025-06-27T04:48:47.202496+00:00 [running]> on host 186147025a3b
[2025-06-27T04:48:55.238+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_pipeline' AIRFLOW_CTX_TASK_ID='Structure_Data_With_Spark' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T04:48:47.202496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-27T04:48:47.202496+00:00'
[2025-06-27T04:48:55.240+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T04:48:55.284+0000] {spark_submit.py:271} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-06-27T04:48:55.285+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --name arrow-spark --verbose /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation
[2025-06-27T04:48:55.289+0000] {spark_submit.py:571} INFO - /home/***/.local/bin/spark-submit: line 27: /opt/bitnami/spark/bin/spark-class: No such file or directory
[2025-06-27T04:48:55.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T04:48:55.314+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --name arrow-spark --verbose /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 127.
[2025-06-27T04:48:55.317+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_processing_pipeline, task_id=Structure_Data_With_Spark, run_id=manual__2025-06-27T04:48:47.202496+00:00, execution_date=20250627T044847, start_date=20250627T044854, end_date=20250627T044855
[2025-06-27T04:48:55.672+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task Structure_Data_With_Spark (Cannot execute: spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --name arrow-spark --verbose /opt/***/include/scripts/structured_data.py /opt/***/data/raw/raw.json /opt/***/data/foundation. Error code is: 127.; 221)
[2025-06-27T04:48:55.698+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-27T04:48:55.735+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T04:48:55.737+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
