[2025-06-27T07:30:36.536+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T07:30:36.617+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_pipeline.Transform_Data_With_Spark manual__2025-06-27T07:24:54.969741+00:00 [queued]>
[2025-06-27T07:30:36.632+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_pipeline.Transform_Data_With_Spark manual__2025-06-27T07:24:54.969741+00:00 [queued]>
[2025-06-27T07:30:36.633+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-27T07:30:36.663+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Transform_Data_With_Spark> on 2025-06-27 07:24:54.969741+00:00
[2025-06-27T07:30:36.672+0000] {standard_task_runner.py:64} INFO - Started process 633 to run task
[2025-06-27T07:30:36.677+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_pipeline', 'Transform_Data_With_Spark', 'manual__2025-06-27T07:24:54.969741+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpblttnl1j']
[2025-06-27T07:30:36.680+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask Transform_Data_With_Spark
[2025-06-27T07:30:36.747+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-27T07:30:36.854+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_processing_pipeline.Transform_Data_With_Spark manual__2025-06-27T07:24:54.969741+00:00 [running]> on host 633b47c55097
[2025-06-27T07:30:37.089+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_pipeline' AIRFLOW_CTX_TASK_ID='Transform_Data_With_Spark' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T07:24:54.969741+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-27T07:24:54.969741+00:00'
[2025-06-27T07:30:37.091+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T07:30:37.156+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-06-27T07:30:37.158+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.appMasterEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.appMasterEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.queue=root.default --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/transform_data.py /opt/***/data/foundation /opt/***/data/trusted
[2025-06-27T07:30:39.026+0000] {spark_submit.py:571} INFO - Using properties file: null
[2025-06-27T07:30:39.168+0000] {spark_submit.py:571} INFO - Parsed arguments:
[2025-06-27T07:30:39.169+0000] {spark_submit.py:571} INFO - master                  yarn
[2025-06-27T07:30:39.170+0000] {spark_submit.py:571} INFO - remote                  null
[2025-06-27T07:30:39.171+0000] {spark_submit.py:571} INFO - deployMode              client
[2025-06-27T07:30:39.172+0000] {spark_submit.py:571} INFO - executorMemory          null
[2025-06-27T07:30:39.173+0000] {spark_submit.py:571} INFO - executorCores           null
[2025-06-27T07:30:39.174+0000] {spark_submit.py:571} INFO - totalExecutorCores      null
[2025-06-27T07:30:39.174+0000] {spark_submit.py:571} INFO - propertiesFile          null
[2025-06-27T07:30:39.175+0000] {spark_submit.py:571} INFO - driverMemory            null
[2025-06-27T07:30:39.176+0000] {spark_submit.py:571} INFO - driverCores             null
[2025-06-27T07:30:39.177+0000] {spark_submit.py:571} INFO - driverExtraClassPath    null
[2025-06-27T07:30:39.178+0000] {spark_submit.py:571} INFO - driverExtraLibraryPath  null
[2025-06-27T07:30:39.179+0000] {spark_submit.py:571} INFO - driverExtraJavaOptions  null
[2025-06-27T07:30:39.180+0000] {spark_submit.py:571} INFO - supervise               false
[2025-06-27T07:30:39.182+0000] {spark_submit.py:571} INFO - queue                   root.default
[2025-06-27T07:30:39.183+0000] {spark_submit.py:571} INFO - numExecutors            null
[2025-06-27T07:30:39.183+0000] {spark_submit.py:571} INFO - files                   null
[2025-06-27T07:30:39.184+0000] {spark_submit.py:571} INFO - pyFiles                 null
[2025-06-27T07:30:39.185+0000] {spark_submit.py:571} INFO - archives                null
[2025-06-27T07:30:39.186+0000] {spark_submit.py:571} INFO - mainClass               null
[2025-06-27T07:30:39.186+0000] {spark_submit.py:571} INFO - primaryResource         file:/opt/***/include/scripts/transform_data.py
[2025-06-27T07:30:39.187+0000] {spark_submit.py:571} INFO - name                    arrow-spark
[2025-06-27T07:30:39.188+0000] {spark_submit.py:571} INFO - childArgs               [/opt/***/data/foundation /opt/***/data/trusted]
[2025-06-27T07:30:39.189+0000] {spark_submit.py:571} INFO - jars                    null
[2025-06-27T07:30:39.190+0000] {spark_submit.py:571} INFO - packages                null
[2025-06-27T07:30:39.191+0000] {spark_submit.py:571} INFO - packagesExclusions      null
[2025-06-27T07:30:39.192+0000] {spark_submit.py:571} INFO - repositories            null
[2025-06-27T07:30:39.193+0000] {spark_submit.py:571} INFO - verbose                 true
[2025-06-27T07:30:39.193+0000] {spark_submit.py:571} INFO - 
[2025-06-27T07:30:39.194+0000] {spark_submit.py:571} INFO - Spark properties used, including those specified through
[2025-06-27T07:30:39.194+0000] {spark_submit.py:571} INFO - --conf and those from the properties file null:
[2025-06-27T07:30:39.196+0000] {spark_submit.py:571} INFO - (spark.executorEnv.HADOOP_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T07:30:39.197+0000] {spark_submit.py:571} INFO - (spark.executorEnv.YARN_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T07:30:39.197+0000] {spark_submit.py:571} INFO - (spark.master,yarn)
[2025-06-27T07:30:39.198+0000] {spark_submit.py:571} INFO - (spark.submit.deployMode,client)
[2025-06-27T07:30:39.198+0000] {spark_submit.py:571} INFO - (spark.yarn.appMasterEnv.HADOOP_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T07:30:39.199+0000] {spark_submit.py:571} INFO - (spark.yarn.appMasterEnv.YARN_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T07:30:39.199+0000] {spark_submit.py:571} INFO - (spark.yarn.queue,root.default)
[2025-06-27T07:30:39.200+0000] {spark_submit.py:571} INFO - 
[2025-06-27T07:30:39.201+0000] {spark_submit.py:571} INFO - 
[2025-06-27T07:30:39.496+0000] {spark_submit.py:571} INFO - Main class:
[2025-06-27T07:30:39.497+0000] {spark_submit.py:571} INFO - org.apache.spark.deploy.PythonRunner
[2025-06-27T07:30:39.498+0000] {spark_submit.py:571} INFO - Arguments:
[2025-06-27T07:30:39.499+0000] {spark_submit.py:571} INFO - file:/opt/***/include/scripts/transform_data.py
[2025-06-27T07:30:39.500+0000] {spark_submit.py:571} INFO - null
[2025-06-27T07:30:39.500+0000] {spark_submit.py:571} INFO - /opt/***/data/foundation
[2025-06-27T07:30:39.501+0000] {spark_submit.py:571} INFO - /opt/***/data/trusted
[2025-06-27T07:30:39.502+0000] {spark_submit.py:571} INFO - Spark config:
[2025-06-27T07:30:39.503+0000] {spark_submit.py:571} INFO - (spark.app.name,arrow-spark)
[2025-06-27T07:30:39.504+0000] {spark_submit.py:571} INFO - (spark.app.submitTime,1751009439469)
[2025-06-27T07:30:39.504+0000] {spark_submit.py:571} INFO - (spark.executorEnv.HADOOP_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T07:30:39.505+0000] {spark_submit.py:571} INFO - (spark.executorEnv.YARN_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T07:30:39.506+0000] {spark_submit.py:571} INFO - (spark.master,yarn)
[2025-06-27T07:30:39.507+0000] {spark_submit.py:571} INFO - (spark.submit.deployMode,client)
[2025-06-27T07:30:39.507+0000] {spark_submit.py:571} INFO - (spark.submit.pyFiles,)
[2025-06-27T07:30:39.508+0000] {spark_submit.py:571} INFO - (spark.yarn.appMasterEnv.HADOOP_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T07:30:39.508+0000] {spark_submit.py:571} INFO - (spark.yarn.appMasterEnv.YARN_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T07:30:39.509+0000] {spark_submit.py:571} INFO - (spark.yarn.isPython,true)
[2025-06-27T07:30:39.510+0000] {spark_submit.py:571} INFO - (spark.yarn.queue,root.default)
[2025-06-27T07:30:39.510+0000] {spark_submit.py:571} INFO - Classpath elements:
[2025-06-27T07:30:39.511+0000] {spark_submit.py:571} INFO - 
[2025-06-27T07:30:39.512+0000] {spark_submit.py:571} INFO - 
[2025-06-27T07:30:39.513+0000] {spark_submit.py:571} INFO - 
[2025-06-27T07:30:40.719+0000] {spark_submit.py:571} INFO - üöÄ Starting data transformation...
[2025-06-27T07:30:40.720+0000] {spark_submit.py:571} INFO - üìç Input path: /opt/***/data/foundation
[2025-06-27T07:30:40.720+0000] {spark_submit.py:571} INFO - üìç Output path: /opt/***/data/trusted
[2025-06-27T07:30:40.844+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:40 INFO SparkContext: Running Spark version 3.5.1
[2025-06-27T07:30:40.846+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:40 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-06-27T07:30:40.847+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:40 INFO SparkContext: Java version 17.0.15
[2025-06-27T07:30:40.953+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-27T07:30:41.083+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO ResourceUtils: ==============================================================
[2025-06-27T07:30:41.084+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-27T07:30:41.085+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO ResourceUtils: ==============================================================
[2025-06-27T07:30:41.086+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SparkContext: Submitted application: TransformData
[2025-06-27T07:30:41.121+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-27T07:30:41.135+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-06-27T07:30:41.137+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-27T07:30:41.208+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SecurityManager: Changing view acls to: ***
[2025-06-27T07:30:41.209+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SecurityManager: Changing modify acls to: ***
[2025-06-27T07:30:41.209+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SecurityManager: Changing view acls groups to:
[2025-06-27T07:30:41.210+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SecurityManager: Changing modify acls groups to:
[2025-06-27T07:30:41.211+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-06-27T07:30:41.572+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO Utils: Successfully started service 'sparkDriver' on port 32875.
[2025-06-27T07:30:41.624+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SparkEnv: Registering MapOutputTracker
[2025-06-27T07:30:41.674+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-27T07:30:41.698+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-27T07:30:41.700+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-27T07:30:41.768+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-27T07:30:41.791+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-96c377ac-2794-4b26-b5b8-5a7b6294df17
[2025-06-27T07:30:41.807+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-27T07:30:41.878+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:41 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-27T07:30:42.073+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:42 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-06-27T07:30:42.169+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:42 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-06-27T07:30:42.452+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:42 INFO DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at resourcemanager/172.18.0.3:8032
[2025-06-27T07:30:43.012+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:43 INFO Configuration: resource-types.xml not found
[2025-06-27T07:30:43.013+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:43 INFO ResourceUtils: Unable to find 'resource-types.xml'.
[2025-06-27T07:30:43.024+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:43 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (8192 MB per container)
[2025-06-27T07:30:43.025+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:43 INFO Client: Will allocate AM container, with 896 MB memory including 384 MB overhead
[2025-06-27T07:30:43.025+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:43 INFO Client: Setting up container launch context for our AM
[2025-06-27T07:30:43.028+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:43 INFO Client: Setting up the launch environment for our AM container
[2025-06-27T07:30:43.036+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:43 INFO Client: Preparing resources for our AM container
[2025-06-27T07:30:43.072+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:43 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
[2025-06-27T07:30:46.166+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:46 INFO Client: Uploading resource file:/tmp/spark-f9f22ab4-36af-4e2a-8bfe-783c93076a39/__spark_libs__4895059689281764692.zip -> hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0006/__spark_libs__4895059689281764692.zip
[2025-06-27T07:30:48.891+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:48 INFO Client: Uploading resource file:/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip -> hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0006/pyspark.zip
[2025-06-27T07:30:48.955+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:48 INFO Client: Uploading resource file:/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip -> hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0006/py4j-0.10.9.7-src.zip
[2025-06-27T07:30:49.188+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO Client: Uploading resource file:/tmp/spark-f9f22ab4-36af-4e2a-8bfe-783c93076a39/__spark_conf__14007698598304123598.zip -> hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0006/__spark_conf__.zip
[2025-06-27T07:30:49.247+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO SecurityManager: Changing view acls to: ***
[2025-06-27T07:30:49.248+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO SecurityManager: Changing modify acls to: ***
[2025-06-27T07:30:49.249+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO SecurityManager: Changing view acls groups to:
[2025-06-27T07:30:49.250+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO SecurityManager: Changing modify acls groups to:
[2025-06-27T07:30:49.250+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-06-27T07:30:49.283+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO Client: Submitting application application_1751006797025_0006 to ResourceManager
[2025-06-27T07:30:49.531+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO Client: Deleted staging directory hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0006
[2025-06-27T07:30:49.534+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 ERROR SparkContext: Error initializing SparkContext.
[2025-06-27T07:30:49.535+0000] {spark_submit.py:571} INFO - org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1751006797025_0006 to YARN : Application application_1751006797025_0006 submitted by user *** to unknown queue: root.default
[2025-06-27T07:30:49.536+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:336)
[2025-06-27T07:30:49.537+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:220)
[2025-06-27T07:30:49.538+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
[2025-06-27T07:30:49.539+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
[2025-06-27T07:30:49.540+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:604)
[2025-06-27T07:30:49.541+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-06-27T07:30:49.541+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-06-27T07:30:49.542+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-06-27T07:30:49.543+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-06-27T07:30:49.544+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-06-27T07:30:49.545+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-06-27T07:30:49.545+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-06-27T07:30:49.546+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-06-27T07:30:49.546+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2025-06-27T07:30:49.548+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-06-27T07:30:49.548+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-06-27T07:30:49.549+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-06-27T07:30:49.550+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-06-27T07:30:49.551+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-06-27T07:30:49.552+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-06-27T07:30:49.553+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO SparkUI: Stopped Spark web UI at http://633b47c55097:4040
[2025-06-27T07:30:49.564+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to send shutdown message before the AM has registered!
[2025-06-27T07:30:49.576+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
[2025-06-27T07:30:49.582+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO YarnClientSchedulerBackend: Shutting down all executors
[2025-06-27T07:30:49.589+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
[2025-06-27T07:30:49.594+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO YarnClientSchedulerBackend: YARN client scheduler backend Stopped
[2025-06-27T07:30:49.629+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-27T07:30:49.656+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO MemoryStore: MemoryStore cleared
[2025-06-27T07:30:49.659+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO BlockManager: BlockManager stopped
[2025-06-27T07:30:49.691+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-27T07:30:49.694+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 WARN MetricsSystem: Stopping a MetricsSystem that is not running
[2025-06-27T07:30:49.702+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-27T07:30:49.742+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO SparkContext: Successfully stopped SparkContext
[2025-06-27T07:30:49.744+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2025-06-27T07:30:49.745+0000] {spark_submit.py:571} INFO - File "/opt/***/include/scripts/transform_data.py", line 170, in <module>
[2025-06-27T07:30:49.754+0000] {spark_submit.py:571} INFO - transform_data(input_path, output_path)
[2025-06-27T07:30:49.755+0000] {spark_submit.py:571} INFO - File "/opt/***/include/scripts/transform_data.py", line 90, in transform_data
[2025-06-27T07:30:49.764+0000] {spark_submit.py:571} INFO - .getOrCreate()
[2025-06-27T07:30:49.766+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 497, in getOrCreate
[2025-06-27T07:30:49.767+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 515, in getOrCreate
[2025-06-27T07:30:49.770+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 203, in __init__
[2025-06-27T07:30:49.773+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 296, in _do_init
[2025-06-27T07:30:49.775+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 421, in _initialize_context
[2025-06-27T07:30:49.779+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
[2025-06-27T07:30:49.783+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-06-27T07:30:49.786+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2025-06-27T07:30:49.788+0000] {spark_submit.py:571} INFO - : org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1751006797025_0006 to YARN : Application application_1751006797025_0006 submitted by user *** to unknown queue: root.default
[2025-06-27T07:30:49.789+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:336)
[2025-06-27T07:30:49.791+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:220)
[2025-06-27T07:30:49.794+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
[2025-06-27T07:30:49.798+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
[2025-06-27T07:30:49.799+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:604)
[2025-06-27T07:30:49.801+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-06-27T07:30:49.802+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-06-27T07:30:49.803+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-06-27T07:30:49.804+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-06-27T07:30:49.806+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-06-27T07:30:49.808+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-06-27T07:30:49.809+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-06-27T07:30:49.811+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-06-27T07:30:49.812+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2025-06-27T07:30:49.813+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-06-27T07:30:49.814+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-06-27T07:30:49.816+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-06-27T07:30:49.817+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-06-27T07:30:49.818+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-06-27T07:30:49.819+0000] {spark_submit.py:571} INFO - 
[2025-06-27T07:30:49.926+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO ShutdownHookManager: Shutdown hook called
[2025-06-27T07:30:49.927+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-f9f22ab4-36af-4e2a-8bfe-783c93076a39
[2025-06-27T07:30:49.938+0000] {spark_submit.py:571} INFO - 25/06/27 07:30:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-af0944e4-e43d-41ca-9689-f8a71abb25be
[2025-06-27T07:30:50.044+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T07:30:50.086+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.appMasterEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.appMasterEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.queue=root.default --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/transform_data.py /opt/***/data/foundation /opt/***/data/trusted. Error code is: 1.
[2025-06-27T07:30:50.095+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_processing_pipeline, task_id=Transform_Data_With_Spark, run_id=manual__2025-06-27T07:24:54.969741+00:00, execution_date=20250627T072454, start_date=20250627T073036, end_date=20250627T073050
[2025-06-27T07:30:50.129+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task Transform_Data_With_Spark (Cannot execute: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.appMasterEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.appMasterEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.queue=root.default --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/transform_data.py /opt/***/data/foundation /opt/***/data/trusted. Error code is: 1.; 633)
[2025-06-27T07:30:50.169+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-27T07:30:50.226+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T07:30:50.240+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
