[2025-06-27T08:02:42.027+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T08:02:42.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_pipeline.Transform_Data_With_Spark manual__2025-06-27T08:01:51.404993+00:00 [queued]>
[2025-06-27T08:02:42.127+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_pipeline.Transform_Data_With_Spark manual__2025-06-27T08:01:51.404993+00:00 [queued]>
[2025-06-27T08:02:42.128+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T08:02:42.158+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Transform_Data_With_Spark> on 2025-06-27 08:01:51.404993+00:00
[2025-06-27T08:02:42.168+0000] {standard_task_runner.py:64} INFO - Started process 549 to run task
[2025-06-27T08:02:42.175+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_pipeline', 'Transform_Data_With_Spark', 'manual__2025-06-27T08:01:51.404993+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdb5hwemz']
[2025-06-27T08:02:42.179+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask Transform_Data_With_Spark
[2025-06-27T08:02:42.253+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-27T08:02:42.368+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_processing_pipeline.Transform_Data_With_Spark manual__2025-06-27T08:01:51.404993+00:00 [running]> on host 3b4e24e60641
[2025-06-27T08:02:42.621+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_pipeline' AIRFLOW_CTX_TASK_ID='Transform_Data_With_Spark' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T08:01:51.404993+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-27T08:01:51.404993+00:00'
[2025-06-27T08:02:42.623+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T08:02:42.713+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-06-27T08:02:42.715+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.appMasterEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.appMasterEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.queue=root.default --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/transform_data.py /opt/***/data/foundation /opt/***/data/trusted
[2025-06-27T08:02:45.114+0000] {spark_submit.py:571} INFO - Using properties file: null
[2025-06-27T08:02:45.270+0000] {spark_submit.py:571} INFO - Parsed arguments:
[2025-06-27T08:02:45.272+0000] {spark_submit.py:571} INFO - master                  yarn
[2025-06-27T08:02:45.273+0000] {spark_submit.py:571} INFO - remote                  null
[2025-06-27T08:02:45.274+0000] {spark_submit.py:571} INFO - deployMode              client
[2025-06-27T08:02:45.275+0000] {spark_submit.py:571} INFO - executorMemory          null
[2025-06-27T08:02:45.276+0000] {spark_submit.py:571} INFO - executorCores           null
[2025-06-27T08:02:45.276+0000] {spark_submit.py:571} INFO - totalExecutorCores      null
[2025-06-27T08:02:45.277+0000] {spark_submit.py:571} INFO - propertiesFile          null
[2025-06-27T08:02:45.278+0000] {spark_submit.py:571} INFO - driverMemory            null
[2025-06-27T08:02:45.279+0000] {spark_submit.py:571} INFO - driverCores             null
[2025-06-27T08:02:45.280+0000] {spark_submit.py:571} INFO - driverExtraClassPath    null
[2025-06-27T08:02:45.281+0000] {spark_submit.py:571} INFO - driverExtraLibraryPath  null
[2025-06-27T08:02:45.282+0000] {spark_submit.py:571} INFO - driverExtraJavaOptions  null
[2025-06-27T08:02:45.283+0000] {spark_submit.py:571} INFO - supervise               false
[2025-06-27T08:02:45.284+0000] {spark_submit.py:571} INFO - queue                   root.default
[2025-06-27T08:02:45.285+0000] {spark_submit.py:571} INFO - numExecutors            null
[2025-06-27T08:02:45.286+0000] {spark_submit.py:571} INFO - files                   null
[2025-06-27T08:02:45.287+0000] {spark_submit.py:571} INFO - pyFiles                 null
[2025-06-27T08:02:45.288+0000] {spark_submit.py:571} INFO - archives                null
[2025-06-27T08:02:45.289+0000] {spark_submit.py:571} INFO - mainClass               null
[2025-06-27T08:02:45.290+0000] {spark_submit.py:571} INFO - primaryResource         file:/opt/***/include/scripts/transform_data.py
[2025-06-27T08:02:45.291+0000] {spark_submit.py:571} INFO - name                    arrow-spark
[2025-06-27T08:02:45.292+0000] {spark_submit.py:571} INFO - childArgs               [/opt/***/data/foundation /opt/***/data/trusted]
[2025-06-27T08:02:45.293+0000] {spark_submit.py:571} INFO - jars                    null
[2025-06-27T08:02:45.293+0000] {spark_submit.py:571} INFO - packages                null
[2025-06-27T08:02:45.294+0000] {spark_submit.py:571} INFO - packagesExclusions      null
[2025-06-27T08:02:45.295+0000] {spark_submit.py:571} INFO - repositories            null
[2025-06-27T08:02:45.296+0000] {spark_submit.py:571} INFO - verbose                 true
[2025-06-27T08:02:45.297+0000] {spark_submit.py:571} INFO - 
[2025-06-27T08:02:45.297+0000] {spark_submit.py:571} INFO - Spark properties used, including those specified through
[2025-06-27T08:02:45.298+0000] {spark_submit.py:571} INFO - --conf and those from the properties file null:
[2025-06-27T08:02:45.299+0000] {spark_submit.py:571} INFO - (spark.executorEnv.HADOOP_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T08:02:45.300+0000] {spark_submit.py:571} INFO - (spark.executorEnv.YARN_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T08:02:45.300+0000] {spark_submit.py:571} INFO - (spark.master,yarn)
[2025-06-27T08:02:45.301+0000] {spark_submit.py:571} INFO - (spark.submit.deployMode,client)
[2025-06-27T08:02:45.302+0000] {spark_submit.py:571} INFO - (spark.yarn.appMasterEnv.HADOOP_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T08:02:45.303+0000] {spark_submit.py:571} INFO - (spark.yarn.appMasterEnv.YARN_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T08:02:45.304+0000] {spark_submit.py:571} INFO - (spark.yarn.queue,root.default)
[2025-06-27T08:02:45.304+0000] {spark_submit.py:571} INFO - 
[2025-06-27T08:02:45.305+0000] {spark_submit.py:571} INFO - 
[2025-06-27T08:02:45.633+0000] {spark_submit.py:571} INFO - Main class:
[2025-06-27T08:02:45.634+0000] {spark_submit.py:571} INFO - org.apache.spark.deploy.PythonRunner
[2025-06-27T08:02:45.635+0000] {spark_submit.py:571} INFO - Arguments:
[2025-06-27T08:02:45.636+0000] {spark_submit.py:571} INFO - file:/opt/***/include/scripts/transform_data.py
[2025-06-27T08:02:45.637+0000] {spark_submit.py:571} INFO - null
[2025-06-27T08:02:45.638+0000] {spark_submit.py:571} INFO - /opt/***/data/foundation
[2025-06-27T08:02:45.639+0000] {spark_submit.py:571} INFO - /opt/***/data/trusted
[2025-06-27T08:02:45.641+0000] {spark_submit.py:571} INFO - Spark config:
[2025-06-27T08:02:45.642+0000] {spark_submit.py:571} INFO - (spark.app.name,arrow-spark)
[2025-06-27T08:02:45.643+0000] {spark_submit.py:571} INFO - (spark.app.submitTime,1751011365605)
[2025-06-27T08:02:45.644+0000] {spark_submit.py:571} INFO - (spark.executorEnv.HADOOP_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T08:02:45.645+0000] {spark_submit.py:571} INFO - (spark.executorEnv.YARN_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T08:02:45.646+0000] {spark_submit.py:571} INFO - (spark.master,yarn)
[2025-06-27T08:02:45.646+0000] {spark_submit.py:571} INFO - (spark.submit.deployMode,client)
[2025-06-27T08:02:45.647+0000] {spark_submit.py:571} INFO - (spark.submit.pyFiles,)
[2025-06-27T08:02:45.649+0000] {spark_submit.py:571} INFO - (spark.yarn.appMasterEnv.HADOOP_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T08:02:45.650+0000] {spark_submit.py:571} INFO - (spark.yarn.appMasterEnv.YARN_CONF_DIR,/opt/hadoop/etc/hadoop)
[2025-06-27T08:02:45.651+0000] {spark_submit.py:571} INFO - (spark.yarn.isPython,true)
[2025-06-27T08:02:45.652+0000] {spark_submit.py:571} INFO - (spark.yarn.queue,root.default)
[2025-06-27T08:02:45.653+0000] {spark_submit.py:571} INFO - Classpath elements:
[2025-06-27T08:02:45.654+0000] {spark_submit.py:571} INFO - 
[2025-06-27T08:02:45.656+0000] {spark_submit.py:571} INFO - 
[2025-06-27T08:02:45.657+0000] {spark_submit.py:571} INFO - 
[2025-06-27T08:02:48.644+0000] {spark_submit.py:571} INFO - üöÄ Starting data transformation...
[2025-06-27T08:02:48.645+0000] {spark_submit.py:571} INFO - üìç Input path: /opt/***/data/foundation
[2025-06-27T08:02:48.646+0000] {spark_submit.py:571} INFO - üìç Output path: /opt/***/data/trusted
[2025-06-27T08:02:48.804+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:48 INFO SparkContext: Running Spark version 3.5.1
[2025-06-27T08:02:48.809+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:48 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-06-27T08:02:48.810+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:48 INFO SparkContext: Java version 17.0.15
[2025-06-27T08:02:48.906+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-27T08:02:49.052+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO ResourceUtils: ==============================================================
[2025-06-27T08:02:49.053+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-27T08:02:49.054+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO ResourceUtils: ==============================================================
[2025-06-27T08:02:49.055+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SparkContext: Submitted application: TransformData
[2025-06-27T08:02:49.082+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-27T08:02:49.095+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-06-27T08:02:49.099+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-27T08:02:49.174+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SecurityManager: Changing view acls to: ***
[2025-06-27T08:02:49.175+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SecurityManager: Changing modify acls to: ***
[2025-06-27T08:02:49.177+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SecurityManager: Changing view acls groups to:
[2025-06-27T08:02:49.178+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SecurityManager: Changing modify acls groups to:
[2025-06-27T08:02:49.179+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-06-27T08:02:49.530+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO Utils: Successfully started service 'sparkDriver' on port 41747.
[2025-06-27T08:02:49.592+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SparkEnv: Registering MapOutputTracker
[2025-06-27T08:02:49.672+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-27T08:02:49.712+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-27T08:02:49.715+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-27T08:02:49.841+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-27T08:02:49.875+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-55a771ab-db3c-4805-8ec5-fce652946a99
[2025-06-27T08:02:49.903+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-27T08:02:49.995+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:49 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-27T08:02:50.226+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:50 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-06-27T08:02:50.340+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:50 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-06-27T08:02:50.688+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:50 INFO DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at resourcemanager/172.18.0.3:8032
[2025-06-27T08:02:51.354+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:51 INFO Configuration: resource-types.xml not found
[2025-06-27T08:02:51.355+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:51 INFO ResourceUtils: Unable to find 'resource-types.xml'.
[2025-06-27T08:02:51.368+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:51 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (8192 MB per container)
[2025-06-27T08:02:51.369+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:51 INFO Client: Will allocate AM container, with 896 MB memory including 384 MB overhead
[2025-06-27T08:02:51.370+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:51 INFO Client: Setting up container launch context for our AM
[2025-06-27T08:02:51.374+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:51 INFO Client: Setting up the launch environment for our AM container
[2025-06-27T08:02:51.390+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:51 INFO Client: Preparing resources for our AM container
[2025-06-27T08:02:51.447+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:51 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
[2025-06-27T08:02:55.114+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:55 INFO Client: Uploading resource file:/tmp/spark-a67e3ef2-47cd-4f20-9d67-adc4980c771c/__spark_libs__18225005452377659643.zip -> hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0008/__spark_libs__18225005452377659643.zip
[2025-06-27T08:02:58.641+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:58 INFO Client: Uploading resource file:/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip -> hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0008/pyspark.zip
[2025-06-27T08:02:58.698+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:58 INFO Client: Uploading resource file:/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip -> hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0008/py4j-0.10.9.7-src.zip
[2025-06-27T08:02:58.982+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:58 INFO Client: Uploading resource file:/tmp/spark-a67e3ef2-47cd-4f20-9d67-adc4980c771c/__spark_conf__2571929391684146094.zip -> hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0008/__spark_conf__.zip
[2025-06-27T08:02:59.048+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO SecurityManager: Changing view acls to: ***
[2025-06-27T08:02:59.049+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO SecurityManager: Changing modify acls to: ***
[2025-06-27T08:02:59.049+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO SecurityManager: Changing view acls groups to:
[2025-06-27T08:02:59.050+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO SecurityManager: Changing modify acls groups to:
[2025-06-27T08:02:59.050+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-06-27T08:02:59.096+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO Client: Submitting application application_1751006797025_0008 to ResourceManager
[2025-06-27T08:02:59.419+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO Client: Deleted staging directory hdfs://namenode:9000/user/***/.sparkStaging/application_1751006797025_0008
[2025-06-27T08:02:59.423+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 ERROR SparkContext: Error initializing SparkContext.
[2025-06-27T08:02:59.424+0000] {spark_submit.py:571} INFO - org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1751006797025_0008 to YARN : Application application_1751006797025_0008 submitted by user *** to unknown queue: root.default
[2025-06-27T08:02:59.426+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:336)
[2025-06-27T08:02:59.429+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:220)
[2025-06-27T08:02:59.431+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
[2025-06-27T08:02:59.433+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
[2025-06-27T08:02:59.434+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:604)
[2025-06-27T08:02:59.435+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-06-27T08:02:59.437+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-06-27T08:02:59.438+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-06-27T08:02:59.440+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-06-27T08:02:59.441+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-06-27T08:02:59.442+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-06-27T08:02:59.443+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-06-27T08:02:59.445+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-06-27T08:02:59.446+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2025-06-27T08:02:59.447+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-06-27T08:02:59.448+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-06-27T08:02:59.449+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-06-27T08:02:59.450+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-06-27T08:02:59.451+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-06-27T08:02:59.453+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-06-27T08:02:59.466+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO SparkUI: Stopped Spark web UI at http://3b4e24e60641:4040
[2025-06-27T08:02:59.482+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to send shutdown message before the AM has registered!
[2025-06-27T08:02:59.490+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
[2025-06-27T08:02:59.498+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO YarnClientSchedulerBackend: Shutting down all executors
[2025-06-27T08:02:59.510+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
[2025-06-27T08:02:59.516+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO YarnClientSchedulerBackend: YARN client scheduler backend Stopped
[2025-06-27T08:02:59.572+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-27T08:02:59.595+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO MemoryStore: MemoryStore cleared
[2025-06-27T08:02:59.596+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO BlockManager: BlockManager stopped
[2025-06-27T08:02:59.613+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-27T08:02:59.615+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 WARN MetricsSystem: Stopping a MetricsSystem that is not running
[2025-06-27T08:02:59.620+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-27T08:02:59.653+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO SparkContext: Successfully stopped SparkContext
[2025-06-27T08:02:59.656+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2025-06-27T08:02:59.657+0000] {spark_submit.py:571} INFO - File "/opt/***/include/scripts/transform_data.py", line 170, in <module>
[2025-06-27T08:02:59.661+0000] {spark_submit.py:571} INFO - transform_data(input_path, output_path)
[2025-06-27T08:02:59.662+0000] {spark_submit.py:571} INFO - File "/opt/***/include/scripts/transform_data.py", line 90, in transform_data
[2025-06-27T08:02:59.665+0000] {spark_submit.py:571} INFO - .getOrCreate()
[2025-06-27T08:02:59.666+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 497, in getOrCreate
[2025-06-27T08:02:59.668+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 515, in getOrCreate
[2025-06-27T08:02:59.669+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 203, in __init__
[2025-06-27T08:02:59.671+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 296, in _do_init
[2025-06-27T08:02:59.672+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 421, in _initialize_context
[2025-06-27T08:02:59.674+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
[2025-06-27T08:02:59.675+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-06-27T08:02:59.678+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2025-06-27T08:02:59.679+0000] {spark_submit.py:571} INFO - : org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1751006797025_0008 to YARN : Application application_1751006797025_0008 submitted by user *** to unknown queue: root.default
[2025-06-27T08:02:59.681+0000] {spark_submit.py:571} INFO - at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:336)
[2025-06-27T08:02:59.682+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:220)
[2025-06-27T08:02:59.683+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
[2025-06-27T08:02:59.684+0000] {spark_submit.py:571} INFO - at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:235)
[2025-06-27T08:02:59.686+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:604)
[2025-06-27T08:02:59.687+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-06-27T08:02:59.688+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-06-27T08:02:59.689+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-06-27T08:02:59.690+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-06-27T08:02:59.691+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-06-27T08:02:59.692+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-06-27T08:02:59.693+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-06-27T08:02:59.694+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-06-27T08:02:59.695+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2025-06-27T08:02:59.696+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-06-27T08:02:59.697+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-06-27T08:02:59.698+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-06-27T08:02:59.699+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-06-27T08:02:59.700+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-06-27T08:02:59.701+0000] {spark_submit.py:571} INFO - 
[2025-06-27T08:02:59.781+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO ShutdownHookManager: Shutdown hook called
[2025-06-27T08:02:59.782+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO ShutdownHookManager: Deleting directory /tmp/spark-64d4ee22-9469-4de4-a340-59cbd7b8b569
[2025-06-27T08:02:59.792+0000] {spark_submit.py:571} INFO - 25/06/27 08:02:59 INFO ShutdownHookManager: Deleting directory /tmp/spark-a67e3ef2-47cd-4f20-9d67-adc4980c771c
[2025-06-27T08:02:59.906+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T08:02:59.999+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.appMasterEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.appMasterEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.queue=root.default --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/transform_data.py /opt/***/data/foundation /opt/***/data/trusted. Error code is: 1.
[2025-06-27T08:03:00.013+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_processing_pipeline, task_id=Transform_Data_With_Spark, run_id=manual__2025-06-27T08:01:51.404993+00:00, execution_date=20250627T080151, start_date=20250627T080242, end_date=20250627T080300
[2025-06-27T08:03:00.083+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task Transform_Data_With_Spark (Cannot execute: /home/***/.local/lib/python3.10/site-packages/pyspark/bin/spark-submit --master yarn --conf spark.master=yarn --conf spark.submit.deployMode=client --conf spark.yarn.appMasterEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.appMasterEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.YARN_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.executorEnv.HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop --conf spark.yarn.queue=root.default --name arrow-spark --verbose --queue root.default /opt/***/include/scripts/transform_data.py /opt/***/data/foundation /opt/***/data/trusted. Error code is: 1.; 549)
[2025-06-27T08:03:00.105+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-27T08:03:00.178+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T08:03:00.181+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
